name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install dependencies
      run: |
        yarn install

    - name: Run unit and integration tests
      run: |
        yarn test
    - name: Upload test coverage report to Codecov
    - uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/
        flags: unittests
        fail_ci_if_error: true
        verbose: true
